const books = [
    {
        id: 1,
        bookName: "The Da Vinci Code",
        bookImg: "https://cdn.kobo.com/book-images/fdf06d9a-d900-48dd-94fb-1c14eb5b94ba/1200/1200/False/the-da-vinci-code.jpg",
        author: "Dan Brown",
        genre: "Mystery, Detective fiction, Conspiracy fiction, Thriller",
        rating: "3.91",
        language: "English",
        price: 449,
        oriPrice: 599,
        type: "fiction, best, author"
    },
    {
        id: 2,
        bookName: "Angels & Demons",
        bookImg: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1696691404i/960.jpg",
        author: "Dan Brown",
        genre: "Mystery-thriller",
        rating: "3.94",
        language: "English",
        price: 449,
        oriPrice: 599,
        type: "fiction, author"
    },
    {
        id: 3,
        bookName: "Digital Fortress",
        bookImg: "https://m.media-amazon.com/images/I/71MP+kZmyEL._AC_UF1000,1000_QL80_.jpg",
        author: "Dan Brown",
        genre: "Mystery, Techno-thriller",
        rating: "3.69",
        language: "English",
        price: 449,
        oriPrice: 599,
        type: "fiction, author"
    },
    {
        id: 4,
        bookName: "Deception Point",
        bookImg: "https://mangaloreblog.files.wordpress.com/2015/11/deception-point.jpg",
        author: "Dan Brown",
        genre: "Mystery",
        rating: "3.75",
        language: "English",
        price: 449,
        oriPrice: 599,
        type: "fiction, author"
    },
    
    {
        id: 5,
        bookName: "Inferno",
        bookImg: "https://m.media-amazon.com/images/I/81Kjb+TgdSL._AC_UF1000,1000_QL80_.jpg",
        author: "Dan Brown",
        genre: "Mystery, Conspiracy fiction, Thriller",
        rating: "3.88",
        language: "English",
        price: 449,
        oriPrice: 599,
        type: "fiction, author"
    },
    {
        id: 6,
        bookName: "Atomic Habits",
        bookImg: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/81YkqyaFVEL._AC_UF1000,1000_QL80_.jpg",
        author: "James Clear",
        genre: "Self-Help",
        rating: "4.36",
        language: "English",
        price: 399,
        oriPrice: 549,
        type: "nonFiction, best"
    },
    {
        id: 7,
        bookName: "Ikigai",
        bookImg: "https://images.penguinrandomhouse.com/cover/9780143130727",
        author: "Francesc Miralles, Hector Garcia ",
        genre: "Self-Help",
        rating: "3.87",
        language: "English",
        price: 359,
        oriPrice: 499,
        type: "nonFiction, best"
    },
    {
        id: 8,
        bookName: "How to win friends and influence people",
        bookImg: "https://rukminim2.flixcart.com/image/850/1000/kwi5evk0/regionalbooks/7/d/f/how-to-win-friends-and-influence-people-original-imag964nvzaxkrya.jpeg?q=90",
        author: "Dale Carnegie",
        genre: "Self-Help",
        rating: "4.22",
        language: "English",
        price: 399,
        oriPrice: 499,
        type: "nonFiction, best"
    },
    {
        id: 9,
        bookName: "And Then There Were None",
        bookImg: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/81QbgfCoVXL._AC_UF1000,1000_QL80_.jpg",
        author: "Agatha Christie",
        genre: "Mystery, crime, psychological thriller",
        rating: "4.28",
        price: 429,
        oriPrice: 549,
        type: "fiction, best, author"
    },
    {
        id: 10,
        bookName: "All Good People Here",
        bookImg: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/811+SQrjv9L._AC_UF1000,1000_QL80_.jpg",
        author: "Ashley Flowers",
        genre: "Suspense, thriller, crime fiction",
        rating: "3.85",
        language: "English",
        price: 459,
        oriPrice: 659,
        type: "fiction"
    },
    {
        id: 11,
        bookName: "The Last to Vanish",
        bookImg: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1657043567i/59345248.jpg",
        author: "Megan Miranda",
        genre: "Mystery, Thriller",
        rating: "3.56",
        language: "English",
        price: 399,
        oriPrice: 559,
        type: "fiction"
    },
    {
        id: 12,
        bookName: "One of Us Is Lying",
        bookImg: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/81Moou8B7RL._AC_UF1000,1000_QL80_.jpg",
        author: "Karen M. McManus",
        genre: "Mystery, Young Adult, Thriller",
        rating: "3.95",
        language: "English",
        price: 399,
        oriPrice: 459,
        type: "fiction"
    },
    {
        id: 13,
        bookName: "It Ends with us",
        bookImg: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1688011813i/27362503.jpg",
        author: "Colleen Hoover",
        language: "English",
        price: 499,
        oriPrice: 799,
        type: "fiction, best, new"
    },
    {
        id: 14,
        bookName: "The Book of Life",
        bookImg: "https://cdn.kobo.com/book-images/b07fd048-853c-42fe-8b1d-a04a3d1de3a7/353/569/90/False/the-book-of-life-25.jpg",
        author: "Deborah Harkness",
        language: "English",
        price: 449,
        oriPrice: 599,
        type: "fiction, new"
    },
    {
        id: 15,
        bookName: "Book of Night",
        bookImg: "https://blackholly.com/wp-content/uploads/2021/07/Black_Book-of-Night_Final-Cover-800x1216.jpg",
        author: "Holly Black",
        language: "English",
        price: 439,
        oriPrice: 599,
        type: "fiction, new"
    },
    {
        id: 16,
        bookName: "Alchemist",
        bookImg: "https://cdn.kobo.com/book-images/6ab9b1f1-2d77-4cfa-992a-d95188c75985/1200/1200/False/a-teacher-s-guide-to-the-alchemist.jpg",
        author: "Paulo Coelho",
        language: "English",
        price: 299,
        oriPrice: 499,
        type: "fiction, new"
    },
    {
        id: 17,
        bookName: "பொன்னியின் செல்வன், முழுத்தொகுப்பு",
        bookImg: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1550976166i/1108124.jpg",
        author: "Kalki",
        genre: "Fiction, Historical Fiction, Classics",
        rating: "4.70",
        language: "Tamil",
        price: 599,
        oriPrice: "1,299",
        type: "fiction, best, author"
    },
    {
        id: 18,
        bookName: "Parthiban Kanavu- Dream of Parthiban",
        bookImg: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1550688675l/109330.jpg",
        author: "Kalki",
        genre: "Fiction, Historical Fiction, Classics, Historical",
        rating: "4.27",
        language: "Tamil",
        price: 559,
        oriPrice: "1,199",
        type: "fiction, author"
    },
    {
        id: 19,
        bookName: "Marakkave Ninaikiren",
        bookImg: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/410CrFxh32L._AC_UF1000,1000_QL80_.jpg",
        author: "Maari Selvaraj",
        genre: "Short Stories",
        rating: "4.55",
        language: "Tamil",
        price: 459,
        oriPrice: 799,
        type: "fiction"
    },
    {
        id: 20,
        bookName: "Hundraåringen som klev ut genom fönstret och försvann",
        bookImg: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1510447566i/36578942.jpg",
        author: "Jonas Jonasson",
        genre: "Fiction, Contemporary, Historical Fiction, Humor, Adventure",
        rating: "3.82",
        language: "Swedish",
        price: 459,
        oriPrice: 899,
        type: "fiction"
    },
    {
        id: 21,
        bookName: "A Man Called Ove",
        bookImg: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1405259930i/18774964.jpg",
        author: "Fredrik Backman",
        genre: "Fiction, Contemporary, Humor, Adult Fiction",
        rating: "4.38",
        language: "Swedish",
        price: 429,
        oriPrice: 659,
        type: "fiction, best"
    },
]

export default books